name: Scheduled Report Delivery

on:
  schedule:
    # Run every 15 minutes to check for scheduled reports
    - cron: '0,15,30,45 * * * *'
  workflow_dispatch: # Allow manual triggering
  push:
    branches: [ with_scheduler ]  # Only run on with_scheduler branch

jobs:
  send-reports:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Send scheduled reports
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        DELIVERY_TEST_SLACK_DEFAULT_CHANNEL_ID: ${{ secrets.DELIVERY_TEST_SLACK_DEFAULT_CHANNEL_ID }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPO_OWNER: ${{ secrets.GITHUB_REPO_OWNER }}
        GITHUB_REPO_NAME: ${{ secrets.GITHUB_REPO_NAME }}
        GITHUB_BRANCH: ${{ secrets.GITHUB_BRANCH }}
        GITHUB_ACTIONS: true
      run: |
        python cron_sender.py
    
    - name: Commit any changes to reports
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff --staged --quiet || git commit -m "Update reports after scheduled delivery"
        git push || true
