name: Scheduled Report Delivery

on:
  schedule:
    # Run every 15 minutes during business hours only (08:00-22:00 JST)
    # This runs at minute 0, 15, 30, 45 of every hour from 08:00 to 21:45 JST
    - cron: '0,15,30,45 23,0-14 * * *'  # 08:00-22:59 JST (converted to UTC: 23:00, 00:00-14:59)
  workflow_dispatch: # Allow manual triggering
  push:
    branches: [ with_scheduler ]  # Only run on with_scheduler branch

permissions:
  contents: write

jobs:
  send-reports:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Send scheduled reports
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        DELIVERY_TEST_SLACK_DEFAULT_CHANNEL_ID: ${{ secrets.DELIVERY_TEST_SLACK_DEFAULT_CHANNEL_ID }}
        STORAGE_TOKEN: ${{ secrets.STORAGE_TOKEN }}
        GITHUB_REPO_OWNER: KhangaridE
        GITHUB_REPO_NAME: nouhin_client_info
        GITHUB_BRANCH: main
        TZ: Asia/Tokyo
        GITHUB_ACTIONS: true
      run: |
        python cron_sender.py

    - name: Run automatic deliveries
      run: |
        python -c "from app.automatic_delivery_manager import automatic_delivery_manager; automatic_delivery_manager.process_automatic_deliveries()"
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        DELIVERY_TEST_SLACK_DEFAULT_CHANNEL_ID: ${{ secrets.DELIVERY_TEST_SLACK_DEFAULT_CHANNEL_ID }}
        STORAGE_TOKEN: ${{ secrets.STORAGE_TOKEN }}
        GITHUB_REPO_OWNER: KhangaridE
        GITHUB_REPO_NAME: nouhin_client_info
        GITHUB_BRANCH: main
        TZ: Asia/Tokyo
        GITHUB_ACTIONS: true
        GOOGLE_SHEETS_STATUS_URL: ${{ secrets.GOOGLE_SHEETS_STATUS_URL }}
        GOOGLE_SHEETS_METADATA_URL: ${{ secrets.GOOGLE_SHEETS_METADATA_URL }}
    
    - name: Commit any changes to reports
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff --staged --quiet || git commit -m "Update reports after scheduled delivery"
        git push || true
